### ISSUE TITLE
老哥求助，都搭建好后，运行app.py，扫码提示微信版本过低

### ISSUE THREAD

**Issue by namas0312** [Tishon1532/chatgpt-on-wechat-win#7]
感谢各位，哥哥姐姐，百度google了一大圈，就是无法解决扫码提示微信版本过低的问题，搜索过github有个项目是ntchat2，里面有部分语句显示可以通过wechat.open(smart=False, faked_wechat_version="3.9.10.19")，绕过检测，但由于本人才疏学浅，不知如何将此段代码整合到app.py内，特无奈伸手，谢谢大佬

**Comment by ignore-anonymous** [comment]
channel/wechatnt/nt_run.py
就改这里

**Comment by namas0312** [comment]
> channel/wechatnt/ntchat_channel.py 就改这里 startup方法

收到，万分感谢，我等一下试试，再次感谢
