### ISSUE TITLE
ntchat容易封号吗？应该有什么注意的哈

### ISSUE THREAD

**Issue by doane2002cn** [Tishon1532/chatgpt-on-wechat-win#8]
此外，如果我已经有项目在 cow 上面，想移植过来的话，我应该关注修改哪些文件，多谢！

**Comment by Tishon1532** [comment]
> 此外，如果我已经有项目在 cow 上面，想移植过来的话，我应该关注修改哪些文件，多谢！

cow怎么配置本项目就怎么配置。
